---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
        cache_valid_time: 3600
  tasks:
    - name: Include bind
      include_role:
        name: '{{cookiecutter.git_user}}.{{cookiecutter.role_name}}'
...
